-- LEVEL2 동명 동물 수 찾기 (GROUP BY)
-- 이름이 2번 이상 나온 (GROUP - HAVING)
-- NULL은 제외, WHERE IS NOT NULL

SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(NAME) >= 2
ORDER BY NAME;