-- LEVEL 1 12세 이하인 여자 환자 목록 출력하기 (SELECT)

-- 주의 NULL인거는 NONE이라고 출력하고 싶을 때
-- CASE문 사용 가능
-- CASE WHEN TLNO IS NULL THEN 'NONE' ELSE TLNO

SELECT PT_NAME, PT_NO, GEND_CD, AGE, COALESCE(TLNO, 'NONE') AS TLNO
FROM PATIENT 
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME ASC;
